api:
  - changed-files:
      - any-glob-to-any-file:
          - "api/**

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "api/tests/**"
          - "chart/tests/**"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "api/Dockerfile"
          - "api/.dockerignore"


dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "api/requirements.txt"
          - "api/requirements-dev.txt"

helm:
  - changed-files:
      - any-glob-to-any-file:
          - "chart/**"

scripts:
  - changed-files:
      - any-glob-to-any-file: "scripts/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
