api:
  - changed-files:
  - any-glob-to-any-file:
      - 'api/**'

chart:
  - changed-files:
    - any-glob-to-any-file:
      - 'chart/**'

docs:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'

scripts:
  - changed-files:
    - any-glob-to-any-file:
      - 'scripts/**'

deps:
  - changed-files:
    - any-glob-to-any-file:
      - 'requirements*'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'