apiVersion: v1
entries:
  aodb:
  - apiVersion: v2
    appVersion: 1.5.5
    created: "2026-08-17T19:03:23.574326968Z"
    description: Helm chart for aodb
    digest: b09234ad42dab4364e52d1bc626ccf0686d219cbd35fe63651041fa6ec062e98
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.5.5.tgz
    version: 1.5.5
  - apiVersion: v2
    appVersion: 1.5.4
    created: "2026-08-17T19:03:23.573383409Z"
    description: Helm chart for aodb
    digest: dbeeff829e0e2d4ad83515eb0aaabaf997b841ff694f4203db59e4e750cccfdf
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.5.4.tgz
    version: 1.5.4
  - apiVersion: v2
    appVersion: 1.5.1
    created: "2026-08-17T19:03:23.572576111Z"
    description: Helm chart for aodb
    digest: 147d958e79480426fadc9236e9fc411074c2acbce99be3436033516d113ecc79
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.5.1.tgz
    version: 1.5.1
  - apiVersion: v2
    appVersion: 1.5.0
    created: "2026-08-17T19:03:23.572096233Z"
    description: Helm chart for aodb
    digest: 7ae67940982f49dd028702417de6fe4a596d25b31a2ba5cce22b80f1110bcc71
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.5.0.tgz
    version: 1.5.0
  - apiVersion: v2
    appVersion: 1.4.6
    created: "2026-08-17T19:03:23.571652798Z"
    description: Helm chart for aodb
    digest: c9c8a8c8756e32ab1f259af932152529b96f6d97d9ea4974fef81b8312913767
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.4.6.tgz
    version: 1.4.6
  - apiVersion: v2
    appVersion: 1.4.5
    created: "2026-08-17T19:03:23.571231395Z"
    description: Helm chart for aodb
    digest: 94895ef4455aee7d0c4e77ca59eb40e9b9fcb3fb2150eed22fab72e32b762c30
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.4.5.tgz
    version: 1.4.5
  - apiVersion: v2
    appVersion: 1.4.4
    created: "2026-08-17T19:03:23.570815698Z"
    description: Helm chart for aodb
    digest: 3e4f61e2962248dbbae4bb70f0b7d8d7a85bff3353067f4f24f21439f5e2927e
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.4.4.tgz
    version: 1.4.4
  - apiVersion: v2
    appVersion: 1.4.3
    created: "2026-08-17T19:03:23.570399451Z"
    description: Helm chart for aodb
    digest: b433821cc51a8b36cca9d5e75c38bf9b3c83a088271c5f1a9b5ef42529afd4ac
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.4.3.tgz
    version: 1.4.3
  - apiVersion: v2
    appVersion: 1.4.2
    created: "2026-08-17T19:03:23.569958711Z"
    description: Helm chart for aodb
    digest: 4fe18cd7615c29d15b14cac5350612cdb93517ab444f330350789fad94d0b91e
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.4.2.tgz
    version: 1.4.2
  - apiVersion: v2
    appVersion: 1.4.1
    created: "2026-08-17T19:03:23.569537153Z"
    description: Helm chart for aodb
    digest: 02c23cb4eaa791a21182b10d7023af352ba8b684443f6f936d582648b3db098b
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.4.1.tgz
    version: 1.4.1
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2026-08-17T19:03:23.569070254Z"
    description: Helm chart for aodb
    digest: 410e4d87b69fedf89f4853c88253746195e847419a20ce781fddd38e22e6fcc6
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.4.0.tgz
    version: 1.4.0
generated: "2026-08-17T19:03:23.56848593Z"
