apiVersion: v1
entries:
  aodb:
  - apiVersion: v2
    appVersion: 1.7.6
    created: "2026-09-02T22:09:36.437773246Z"
    description: Helm chart for aodb
    digest: 45bbe4d67f028452e2ffb27c2360ec002662eeb234fe81bd51a0c59f2c0796ab
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.7.6.tgz
    version: 1.7.6
  - apiVersion: v2
    appVersion: 1.7.5
    created: "2026-09-02T22:09:36.437130299Z"
    description: Helm chart for aodb
    digest: 59a0f1590b2b2a4b5841ed99b6b363c43105cfa6510201903144cbd3daaa2427
    name: aodb
    type: application
    urls:
    - https://zznathans.github.io/aodb/charts/aodb-1.7.5.tgz
    version: 1.7.5
generated: "2026-09-02T22:09:36.436287925Z"
